### ISSUE TITLE
Reffering to groupHulss[index] len while it is None

### ISSUE THREAD

**Issue by kalmary** [truebelief/artemis_treeiso#4]
Hello Zhouxin,

First I would like to kindly thank you for creating the tool in python and cc plugin. Both did an incredible job for me.

I think, I may have found the bug in python implementation (which might be caused mainly by low quality point cloud data I use).
In treeiso.py file, final_segs() function you define groupHulss list, which elements you overwrite like below:

line 273
```
groupHulls=[None]*nGroups 
for i in range(nGroups):
    groupPts = pcd[groupVGroup[i],:]
    groupFeatures[i, :3]=trimmean(groupPts[:, :3], 0.2) # centroid
    groupFeatures[i, 3] = np.min(groupPts[:, 2]) # elevation
    groupFeatures[i, 4] = np.max(groupPts[:, 2])-min(groupPts[:, 2]) # length
    if len(groupPts) > 3:
        groupHulls[i] = groupPts[ConvexHull(groupPts[:,:2]).vertices,:2]
```

I got into situation when len(grupsPts) is not greater than 3. It causes an error when later len(groupHulls[index]) cannot be given as this item of list is None:

line 350
```
if len(groupHulls[toMergeId]) > 3 and len(groupHulls[remainId]) > 3:
    horizontalOverlapRatio = overlapping(groupHulls[toMergeId], groupHulls[remainId])
else:
    horizontalOverlapRatio = 0.0
```

What is the best approach in this situation? Should set horizontalOverlapRatio = 0. every time None value occurs?

**Comment by truebelief** [comment]
Thanks for raising this issue! I've added code to handle cases where the point count is too low to calculate a convex hull by using bounding boxes instead. The updated treeiso.py is now in the main branch. You can see the minor changes from https://github.com/truebelief/artemis_treeiso/commit/32a2a7cd2d05dc754b261604268f9d83063114b9. Please let me know if you run into any further problems. Just a heads-up: the Python code is much slower than the CC plugin following the latest upgrade.

**Comment by kalmary** [comment]
Thank you for such a quick answer! I will check it in two hours or so and let you know.
I'm aware that the cc plugin is way faster, however the python version is perfect for my use case. I am looking for a way to automate segmentation for larger and multiple datasets.

**Comment by kalmary** [comment]
Seems like it is working now. Thank you again. For now I wonder why last segmentation takes so long and is so memory consuming (most from all three steps), as it was the opposite in cloud compare plugin - it may be data specific

**Comment by kalmary** [comment]
Hello!
It turns out it probably created another bug :(
To make the error more reproductible here's my config of treeiso:
```
PR_REG_STRENGTH1 = 2.0  # lambda1
PR_MIN_NN1 = 10  # K1: key parameter

PR_REG_STRENGTH2 = 4.0  # lambda2: key parameter
PR_MIN_NN2 = 30  # K2: key parameter

PR_DECIMATE_RES1 = 1. # For speed optimization
PR_DECIMATE_RES2 = 1.5  # For speed optimization
PR_MAX_GAP = 1. # Max assumed point gap within a tree due to occlusion

PR_REL_HEIGHT_LENGTH_RATIO = 0.5  # rho
PR_VERTICAL_WEIGHT = 0.5  # w
PR_MIN_NN3 = 20 # trivial
PR_SCORE_CANDIDATE_THRESH = 0.7  # No need to change 0.7
PR_INIT_STEM_REL_LENGTH_THRESH = 1.5  # No need to change 1.5
```
I use data LPine1_demo.laz you provided, but I load only small chunk of it to see how program handles inclomplete data (I don't mind if it would create some exceesive clusters):
```
  with laspy.open(path2file) as f:
      for points in f.chunk_iterator(250_000):
          points = points2numpy(points)
          pcd = numpy2_o3dCLoud(points)
          o3d.visualization.draw_geometries([pcd])

          tree_iso.tree_isolator(points) # here comes threeiso logic. It's basically the same as what has been done in main() of treeiso.py
```
In some scenarios in final_segs():
``
nnClusterCentroids = clusterGroupMap[np.concatenate([clusterMapVGroup[remainId]]),:]
``
index remainId is out of range of clutserMapVGroup. In case of error I got, it was:
``
len(clusterMapVGroup) = 2577, remainId = 2580
``
EDIT:
I convert point cloud to numpy as:
``
points  = np.transpose([points.x,points.y,points.z]) # code behind points2numpy()
``
Sorry, I forgot to mention it before


EDIT2: After investigation and loading point data corect way, but in small chunks (probably often looking like noise) algorithm's having multiple problems with indices being out of range in find_segs()  - chunk_size = 100 000
and create_node_edges() - chunk_size = 10 000. 
As it is chunk_size sensitive It's hard for me to find exact the error when it occurs in multiple places.

**Comment by truebelief** [comment]
No worries! I want to make sure there are no bugs. I replicated what you did using the demo LPine1_demo.laz with the following code:

```
with laspy.open(path_to_las) as f:
    for points in f.chunk_iterator(250_000):
        pcd = np.transpose([points.x, points.y, points.z])
        pcd_o3d = o3d.geometry.PointCloud()
        pcd_o3d.points = o3d.utility.Vector3dVector(pcd)
        # o3d.visualization.draw_geometries([pcd_o3d])

        pcd=pcd-np.mean(pcd[:,:3],axis=0)

        dec_idx_uidx, dec_inverse_idx = decimate_pcd(pcd[:, :3], PR_DECIMATE_RES1)  # reduce points first
        pcd_dec = pcd[dec_idx_uidx]

        # Initial segmentation in 3D
        init_labels=init_segs(pcd_dec)
        # Intermediate segmentation in 2D
        intermediate_labels=intermediate_segs(np.concatenate([pcd_dec,init_labels[:,np.newaxis]],axis=-1))
        # Final segmentation based on segment similarity
        labels=final_segs(np.concatenate([pcd_dec,init_labels[:,np.newaxis],intermediate_labels[:,np.newaxis]],axis=-1))
```

I also got an error in the final_segs step, though my error was different. I've updated the code in the [new branch](https://github.com/truebelief/artemis_treeiso/tree/treeiso_python_testing) [630ae12c2509196eeadc781d3f4939461210023b], and the error should now be fixed. Please make sure not to change the point IDs of init_labels and intermediate_labels before running final_segs, as these labels require a continuous range from 0 to N. If you still run into any issues, please let me know.

I'm also working on incorporating the faster C++ version into the pip package with prebuilt wheels so that users can simply do import treeiso without needing to compile anything.

**Comment by kalmary** [comment]
Thank you! Unfortunatelly the issue persists. I made sure to comply with loading you specified, not to modify indexing between each segmentation, and kept segmentation parameters from your update.
Let me paste problematic part in one block (it's not too long):
```
print('groupFeatures[remainIds, :2].shape: ', groupFeatures[remainIds, :2].shape)
        kdtree = cKDTree(groupFeatures[remainIds, :2])
        _, groupNNIdx = kdtree.query(groupFeatures[toMergeIds, :2], k=min(PR_MIN_NN3, len(remainIds)))
        print('groupNNIdx.shape', groupNNIdx.shape)
        print('len(toMergeIds)', len(toMergeIds))
        
        # first problem. I did some simple fix
        if groupNNIdx.ndim==1: # sometimes its (2,) and its .shape[1] doesnt exist
            groupNNIdx = groupNNIdx.reshape(1, -1)
        print('POST FIX: groupNNIdx.shape', groupNNIdx.shape)

        # Calculate similarity score based on gaps and overlaps
        for i,toMergeId in enumerate(toMergeIds):
            currentClusterCentroids = clusterGroupMap[np.concatenate([clusterMapVGroup[toMergeId]]),:]
            nNNs = groupNNIdx.shape[1]
            filterMetrics = np.zeros([nNNs, 5])
            for j in range(nNNs):
                print('i, j', i, j)
                remainId = remainIds[groupNNIdx[i, j]] # here index i is out of range as (after my 'fix') groupNNIdx.shape=(1, 2)
```
Data was loaded in 250 000 chunks. 

Edit0:
Of course I'd be interested in using package-like version! However at this moment I am short with time for implementing it into a project I develop. That's why I try so hard to make it work with the current shape of code. Again, thank you for your hard work and help!

**Comment by truebelief** [comment]
Before I am testing this again, have you updated the final_segs function based on the new branch? Multiple spots needs to update about the knn query results. It seems odd that I used the same file and chunk loop for testing.

**Comment by kalmary** [comment]
Yes, I swapped whole code from the latest branch and just modified loading part to make it looped. As it was really late yesterday I may have missed something obvious. Gonna test it again and reach out to you

**Comment by kalmary** [comment]
I tested the code with latest files downloaded from repository (no parameters changed). Only part I have changed is file loading (chunking with various chunk_size):
```
      path_input = 'LPine1_demo.laz'
    chunk_range = [10_000, 50_000, 100_000, 300_000, 500_000, 700_000, 1_000_000]
    for chunk_size in chunk_range:
        with laspy.open(path_input) as f:
            chunk_iterator = 0
            for points in f.chunk_iterator(chunk_size):
                chunk_iterator+=1
                print('chunk: ', chunk_iterator, 'chunk size: ', chunk_size)
                print('*******Processing*******')

                pcd=np.transpose([points.x,points.y,points.z])
                pcd=pcd-np.mean(pcd[:,:3],axis=0)

                dec_idx_uidx, dec_inverse_idx = decimate_pcd(pcd[:, :3], PR_DECIMATE_RES1)  # reduce points first
                pcd_dec = pcd[dec_idx_uidx]

                # Initial segmentation in 3D
                init_labels=init_segs(pcd_dec)

                # Intermediate segmentation in 2D
                intermediate_labels=intermediate_segs(np.concatenate([pcd_dec,init_labels[:,np.newaxis]],axis=-1))

                # Final segmentation based on segment similarity
                labels=final_segs(np.concatenate([pcd_dec,init_labels[:,np.newaxis],intermediate_labels[:,np.newaxis]],axis=-1))
                print('*******End processing*******')
        f.close()
```
Firstly chunk 250_000:
Unfortunately the issue remained. The error and it's context is exactly the same as in the previous comment. 

``
_, groupNNIdx = kdtree.query(groupFeatures[toMergeIds, :2], k=min(PR_MIN_NN3, len(remainIds)))

print(groupNNIdx) #it sometimes outputs (2, ) so cannot find its .shape[1] value
``
Good news is that my yesterday's fix was almost correct. Vector should be reshaped to be vertical once its ndim is 1:
```
if groupNNIdx.ndim ==1:
    groupNNIdx = groupNNIdx.reshape(1, -1)
```
With this 2 lines of code (repeated twice as groupNNIdx is determined twice in final_segs()),
the above error seems to be gone.

Chunk 10_000:
I got error in:
```
line 161, in create_node_edges
    nn_dist = tree.query(points[v_group[nv], :3], k=1)
                                ~~~~~~~^^^^
IndexError: list index out of range
```
nv in my case is 16, and len(v_group) is also 16. I have no idea how to fix this one :((


Chunk 50_000:
Error message is:
```
line 398, in final_segs
    currentClusterCentroids = clusterGroupMap[np.concatenate(clusterMapVGroup[unmergeId]),:]
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zero-dimensional arrays cannot be concatenated
```

In this one fix may be pretty simple:
``
        currentClusterCentroids = clusterGroupMap[np.concatenate(np.asarray(clusterMapVGroup[unmergeId]).reshape(1, -1)),:]
``
The same solution both for lines 389 and 393

But then I got an error:
```
line 402, in final_segs
    mergeNNId=groupU[filterMetrics[filterMinSpacingIdx,-1]]
              ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```
groupU = [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
filterMetrics = 
[[2.1433613  0.        ]
 [0.53566364 3.        ]]
filterMinSpacing = 1

As filterMetrics values are floats fix should be (?):
``
mergeNNId=groupU[int(filterMetrics[filterMinSpacingIdx,-1])]
``

Which takes me to another one :D

```
line 392, in final_segs
    mergedRemainId = mergedRemainIds[groupNNIdx[i, j]]
                     ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
IndexError: index 2 is out of bounds for axis 0 with size 2
```
Again no idea what to do here due to limited understanding of point grouping.

For chunk_size 100_000 it looks the same like with 50_000. 
Chunk sizes 250_000, 300_000 and 1_000_000 work flawlessly after fixes I introduced, but chunks 500_000, 700_000 returns the same error as 50_000 and 100_000. 

I know, number of problem I'm describing is mounting. Hopefully above details will make your work less painful. All the lines I am referring to, are the same as in your repository (to help you find them). I'm trying to understand each error, but must admit, my understanding of the method you provided for point clustering  is very limited

**Comment by truebelief** [comment]
What I mean is the code from [this branch](https://github.com/truebelief/artemis_treeiso/blob/treeiso_python_testing/Python/treeiso.py), not the main branch. Did you use this code? It should come with the update like this, similar to your reshape method, but more specific to the case of 1 point due to the format inconsistency from the knn query function.

 groupNNIdx = np.transpose(groupNNIdx)[:, np.newaxis] if groupNNIdx.ndim == 1 else groupNNIdx
    nNNs = groupNNIdx.shape[1]

**Comment by kalmary** [comment]
Oh I didn't see the branch. Now I'm feeling a bit stupid, I was debugging main for 3 hours or so. Thanks, I'll check it asap

**Comment by truebelief** [comment]
No worries. There can be new issues and I just want to make sure we are on the same page

**Comment by kalmary** [comment]
Still no luck unfortunately. I did the update to a new branch but kept loading by multiple chunk sizes. Some issues I discovered in previous comment ocurred again:
For chunk 10_000:
```
                                                    line 161, in create_node_edges
    nn_dist = tree.query(points[v_group[nv], :3], k=1)
                                ~~~~~~~^^^^
IndexError: list index out of range
```
v_group is a list with 16 elements and nv is 16th element. I have also described it in previous comment.

Chunk 50_000, 100_000:
```
line 395, in final_segs
    currentClusterCentroids = clusterGroupMap[np.concatenate(clusterMapVGroup[unmergeId]),:]
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zero-dimensional arrays cannot be concatenated

```
Same as in previous comment. I think it should be np.assaray(clusterMapVGroup[unmergeId]).reshape(1, -1) as inner part is always zero dimensional (I suppose so).

Error after fix:
```
line 408, in final_segs
    mergeNNId=groupU[filterMetrics[filterMinSpacingIdx,-1]]
              ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

```
I think it should be:
``
mergeNNId=groupU[int(filterMetrics[filterMinSpacingIdx,-1])], because filterMetrics' content is float
``

Then:
```
line 398, in final_segs
    mergedRemainId = mergedRemainIds[groupNNIdx[i, j]]
                     ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
IndexError: index 4 is out of bounds for axis 0 with size 2

```
One of errors I have no clear idea how to fix.

After fixes I did, chunks 250_000, 300_000, 750_000, 1_000_000 are working fine (before fix in line 395, chunk 250_000 returned an error described above).
Chunk 500_000, returns an error from line 398 (described above). 
Hope the detailed description will help you D:

**Comment by truebelief** [comment]
I don't have such indexing issue using the chunk loading. May I see you whole code file and your environment settings? Sometimes the python version and OS might have different results.

**Comment by kalmary** [comment]
I use it with python 3.12 on Fedora 41/ Ubuntu 24.04 LTS (depending on where I work from). All packages are the latest ones as I created virtual env on Thursday. Let me just paste the code and all the settings tomorrow. Only one thing I am able to think of right now is maxflow. I didn't compile it from source, but used:
```
pip install PyMaxflow
```

**Comment by kalmary** [comment]
Hi I made a new environment and redownloaded your branch. Issue persists so I attach the code and requirements below. Errors we are discussing mainly occured on Fedora, so I'm sharing its details too:
```
OS: Fedora Linux 41 (KDE Plasma) x86_64

Kernel: Linux 6.13.4-200.fc41.x86_64

``` 
In an hour or two I'll be able to test the same on windows 11. I will also give you the results I got there.

EDIT 0:
The error message (1st chunk_size - 10_000) on Windows 11 is exactly the same. I configured virtual environment with requirements.txt given below.

EDIT 1:
I get the same indexing errors on Ubuntu 24.04 LTS. I guess it may be caused by my environment configuration. The problem is, there is no really the requirements.txt file you mentioned in README (If I'm wrong please correct me). I can't find it in repositiory manually nor by cloning repo, changing dir to Python and then:
``
pip install -r requirements.txt
``
REQUIREMENTS:

[requirements.txt](https://github.com/user-attachments/files/19042683/requirements.txt)

CODE:
```
"""Tree isolation from terrestrial laser scanning point clouds."""

import os
from glob import glob

import laspy
import numpy as np
import numpy_indexed as npi
from scipy.spatial import cKDTree, ConvexHull
from skimage import draw

from cut_pursuit_L2 import cut_pursuit

# Parameters
PR_REG_STRENGTH1 = 1.0  # lambda1
PR_MIN_NN1 = 5  # K1: key parameter

PR_REG_STRENGTH2 = 20  # lambda2: key parameter
PR_MIN_NN2 = 20  # K2: key parameter

PR_DECIMATE_RES1 = 0.05  # For speed optimization
PR_DECIMATE_RES2 = 0.1  # For speed optimization
PR_MAX_GAP = 2.0  # Max assumed point gap within a tree due to occlusion

PR_REL_HEIGHT_LENGTH_RATIO = 0.5  # rho
PR_VERTICAL_WEIGHT = 0.5  # w
PR_MIN_NN3 = 20  # trivial
PR_SCORE_CANDIDATE_THRESH = 0.7  # No need to change
PR_INIT_STEM_REL_LENGTH_THRESH = 1.5  # No need to change


def overlapping(conv_hull1, conv_hull2):
    """Calculate the 2D horizontal overlapping ratio between two convex hulls.

    Args:
        conv_hull1 (numpy.ndarray): First convex hull points, shape (N, 2)
        conv_hull2 (numpy.ndarray): Second convex hull points, shape (M, 2)

    Returns:
        float: Maximum overlapping ratio between the intersection and either hull
    """
    conv_hull1 = np.array(conv_hull1)
    conv_hull2 = np.array(conv_hull2)

    # Arbitrary scale factor to enlarge the mask image
    scale = 10

    # Combine hulls and normalize coordinates to start from (0,0)
    conv_hull_combo = np.vstack((conv_hull1, conv_hull2))
    conv_hull_combo_min = np.min(conv_hull_combo, axis=0)

    # Calculate digitization size
    digitize_size = np.ceil(
        np.max(conv_hull_combo[:, :2] - conv_hull_combo_min, axis=0) * scale
    ) + 10
    digitize_size = digitize_size.astype(int)
    digitize_size = [digitize_size[1], digitize_size[0]]  # Swap for height, width format

    # Scale and shift hull coordinates
    hull1_scaled = (conv_hull1 - conv_hull_combo_min) * scale
    hull2_scaled = (conv_hull2 - conv_hull_combo_min) * scale

    # Create binary masks using polygon
    conv_mask1 = np.zeros(digitize_size, dtype=np.uint8)
    conv_mask2 = np.zeros(digitize_size, dtype=np.uint8)

    # Extract x and y coordinates for both hulls
    r1, c1 = hull1_scaled[:, 1], hull1_scaled[:, 0]
    r2, c2 = hull2_scaled[:, 1], hull2_scaled[:, 0]

    # Create polygon masks using skimage
    rr1, cc1 = draw.polygon(r1, c1)
    rr2, cc2 = draw.polygon(r2, c2)

    conv_mask1[rr1, cc1] = 1
    conv_mask2[rr2, cc2] = 1

    # Calculate intersection mask
    conv_intersect_mask = conv_mask1 & conv_mask2

    # Calculate areas
    intersection_area = np.sum(conv_intersect_mask)
    mask1_area = np.sum(conv_mask1)
    mask2_area = np.sum(conv_mask2)

    # Calculate maximum overlap ratio
    overlap_ratio = max(
        intersection_area / mask1_area,
        intersection_area / mask2_area
    )

    if np.isnan(overlap_ratio):
        overlap_ratio = 0
    return overlap_ratio


def init_segs(pcd):
    """Initialize segments from point cloud data."""
    pcd=pcd[:, :3] - np.mean(pcd[:, :3], axis=0)
    point_count = len(pcd)
    if point_count == 0:
        return False

    kdtree = cKDTree(pcd[:, :3])
    nn_D, nn_idx = kdtree.query(pcd, k=PR_MIN_NN1 + 1)

    # Remove self-connections
    indices = nn_idx[:, 1:]

    # Create edge list
    n_nodes = len(pcd)
    n_obs = 3
    n_edges = n_nodes * PR_MIN_NN1

    eu = np.repeat(np.arange(n_nodes), PR_MIN_NN1)
    ev = indices.ravel()

    y = pcd[:, :3] - np.mean(pcd[:, :3], axis=0)

    # Edge weights following C++ implementation
    edge_weight = np.ones_like(eu)
    node_weight = np.ones(point_count)

    solution, components, in_component, energy_out, time_out = cut_pursuit(
        n_nodes=n_nodes,
        n_edges=n_edges,
        n_obs=n_obs,
        observation=y,
        eu=eu,
        ev=ev,
        edge_weight=edge_weight,
        node_weight=node_weight,
        lambda_=PR_REG_STRENGTH1,
        verbose=True
    )
    return in_component


def create_node_edges(points, k=10, max_distance=0.4):
    """Create node edges from point cloud data.

    Args:
        points: Point cloud data with [x, y, z, init_segs]
        k: Number of nearest neighbors
        max_distance: Max allowed distance for a component not to be considered as an outlier
    """
    _,centroids_idx, inverse_idx = np.unique(points[:, -1], return_index=True,return_inverse=True)
    _, v_group = npi.group_by(points[:, -1].astype(np.int32), np.arange(len(points[:, -1])))

    centroids = np.array([np.mean(points[idx, :3], 0) for idx in v_group])
    kdtree = cKDTree(centroids[:, :3])
    _, indices = kdtree.query(centroids[:, :3], k=k + 1)
    distance_matrix = np.zeros([len(centroids), len(centroids)])-1  #
    for i, v in enumerate(v_group):
        nn_idx = indices[i, 1:]
        tree = cKDTree(points[v, :3])
        distance_matrix[i,i]=0
        for j, nv in enumerate(nn_idx):
            if distance_matrix[i,j]>0:
                continue
            nn_dist = tree.query(points[v_group[nv], :3], k=1)
            distance_matrix[i, nv] = np.min(nn_dist)

    kdtree = cKDTree(points[:,:3])
    nn_D, nn_idx = kdtree.query(points[:,:3], k=k + 1)
    indices = nn_idx[:, 1:]

    eu = np.repeat(np.arange(len(points)), k)
    ev = indices.ravel()

    eu_node=inverse_idx[eu]
    ev_node=inverse_idx[ev]

    distance_pairs=np.transpose([eu,ev,distance_matrix[eu_node,ev_node]])

    distance_pairs=distance_pairs[distance_pairs[:,-1]<max_distance]
    distance_pairs=distance_pairs[distance_pairs[:,-1]>-1]
    return centroids,distance_pairs,centroids_idx,inverse_idx


def intermediate_segs(pcd):
    """Create intermediate segments from point cloud data."""
    pcd[:,:3]=pcd[:,:3]-np.mean(pcd[:,:3],axis=0)
    centroids,distance_pairs,centroids_idx,centroids_inverse_idx=create_node_edges(pcd[:,:4],k=PR_MIN_NN2,max_distance=PR_MAX_GAP)
    point_count=len(pcd)
    if point_count == 0:
        return False

    # Create edge list
    n_nodes = point_count
    n_obs=2
    n_edges=len(distance_pairs)

    # Edge weights based on inverse distance
    edge_weight = 10./((distance_pairs[:,2]+0.01)/0.01)
    node_weight = np.ones(n_nodes)

    # Cut-pursuit based on xy coordinates and 3D minimal point gaps
    solution, components, in_component, energy_out, time_out = cut_pursuit(
        n_nodes=n_nodes,
        n_edges=n_edges,
        n_obs=n_obs,
        observation=pcd[:,:2],
        eu=distance_pairs[:,0],
        ev=distance_pairs[:,1],
        edge_weight=edge_weight,
        node_weight=node_weight,
        lambda_=PR_REG_STRENGTH2,
        verbose=True
    )
    return in_component

def trimmean(x, percent):
    """Calculate the robust mean by trimming outliers.
       Args:
        x: Input array
        percent: Percentage of data to trim from each end
    """
    x = np.asarray(x)
    if x.ndim > 2:
        raise ValueError("Input must be 1-D or 2-D array")
    if not 0 <= percent <= 100:
        raise ValueError("Percent must be between 0 and 100")
    if x.ndim == 1:
        n = len(x)
        k = int(round(n * percent / 100 / 2))
        return np.mean(np.sort(x)[k:n - k])
    else:  # 2-D array
        return np.array([trimmean(col, percent) for col in x.T])

def final_segs(pcd):
    """Create final segments from point cloud data.

    Args:
        pcd: Point cloud data with [x, y, z, init_segs, intermediate_segs]
    """
    pcd=np.concatenate([pcd,pcd[:,-1][:,np.newaxis]],axis=-1)

    # Group smallest clusters based on init_segs
    clusterIdx = pcd[:, -3]
    _,clusterUIdx=np.unique(clusterIdx,return_index=True)
    clusterU, clusterVGroup = npi.group_by(clusterIdx.astype(np.int32), np.arange(len(clusterIdx)))
    centroids=np.vstack([np.mean(pcd[cluster_group_idx, :3], 0) for i,cluster_group_idx in enumerate(clusterVGroup)])

    clusterGroupIds = pcd[:, -1]  # Records final tree IDs per point

    # Group larger segments based on intermediate_segs
    clusterGroupMap=np.concatenate([centroids,pcd[clusterUIdx,-3:-1]],axis=-1)
    clusterMapU, clusterMapV = np.unique(clusterGroupMap[:, -1], return_inverse=True)
    _, clusterMapVGroup = npi.group_by(clusterGroupMap[:, -1].astype(np.int32), np.arange(len(clusterGroupMap[:, -1])))


    iter=1
    toMergeIds=np.array([0,0])
    prevToMergeIds=np.array([0])
    mergedRemainIds=[]
    groupU=[]
    groupVGroup=[]
    groupFeatures=[]

    # Iterative merging
    # Future: Merging one cluster each time can be inefficient and order-specific. A better way is to use graph with edge weights based on the weighted computed metrics, and optimize with the shortest path
    while(len(toMergeIds)!=len(prevToMergeIds) and len(toMergeIds)>0):
        prevToMergeIds=toMergeIds.copy()

        # Group tree segments based on temporal tree IDs (clusterGroupIds)
        groupU,groupV=np.unique(clusterGroupIds,return_inverse=True)
        _,groupVGroup = npi.group_by(clusterGroupIds.astype(np.int32), np.arange(len(clusterGroupIds)))

        # Extract features for each tree segment (e.g. convexhull)
        nGroups=len(groupVGroup)
        if nGroups==1:
            break
        
        groupFeatures=np.zeros([nGroups,5])
        groupHulls=[None]*nGroups
        for i in range(nGroups):
            groupPts = pcd[groupVGroup[i],:]
            groupFeatures[i, :3]=trimmean(groupPts[:, :3], 0.2) # centroid
            groupFeatures[i, 3] = np.min(groupPts[:, 2]) # elevation
            groupFeatures[i, 4] = np.max(groupPts[:, 2])-min(groupPts[:, 2]) # length
            try:
                hull = ConvexHull(groupPts[:, :2])
                groupHulls[i] = groupPts[hull.vertices, :2]
            except Exception:
                # If ConvexHull fails, create a simple bounding box instead
                mins = np.min(groupPts[:, :2], axis=0)
                maxs = np.max(groupPts[:, :2], axis=0)
                groupHulls[i] = np.array([
                    [mins[0], mins[1]],
                    [maxs[0], mins[1]],
                    [maxs[0], maxs[1]],
                    [mins[0], maxs[1]]
                ])
            # if len(groupPts) > 3:
            #     groupHulls[i] = groupPts[ConvexHull(groupPts[:,:2]).vertices,:2]

        # Search nearest k tree segments for each tree segments
        kdtree = cKDTree(groupFeatures[:, :2])
        groupNNCDs, groupNNIdxC = kdtree.query(groupFeatures[:, :2], k=min(len(groupFeatures),PR_MIN_NN3))
        groupNNCDs = np.transpose(groupNNCDs)[:, np.newaxis] if groupNNCDs.ndim == 1 else groupNNCDs
        
        sigmaD=np.mean(groupNNCDs[:,1]) # Mean centroid distance between segments

        toMergeIds=np.zeros(nGroups,dtype=np.int32)

        # Find initial stem segments
        for i in range(nGroups):
            currentGroupFt = groupFeatures[i, 3:5]
            nnGroupId = groupNNIdxC[i, :]
            nnGroupFt = groupFeatures[nnGroupId, 3:5]
            currentGroupRelHt = (currentGroupFt[0] - np.min(nnGroupFt[:, 0])) / currentGroupFt[1]
            # Set flags, for the first iteration, just merge longer segments first; merge remaining segments from the second iteration on
            if np.abs(currentGroupRelHt) > PR_REL_HEIGHT_LENGTH_RATIO:
                if (currentGroupFt[1] / np.median(nnGroupFt[:, 1])) > PR_INIT_STEM_REL_LENGTH_THRESH:
                    toMergeIds[i] = i
                else:
                    toMergeIds[i] = -i
        toMergeLogi=toMergeIds!=0
        remainIds = np.where(~toMergeLogi)[0]
        toMergeIds = toMergeIds[toMergeLogi]
        if (iter == 1) and np.sum(toMergeIds >= 0) > 0:
            toMergeIds=toMergeIds[toMergeIds>0]
        else:
            toMergeIds = np.abs(toMergeIds)

        # Search nearest k tree segments for remaining segments
        kdtree = cKDTree(groupFeatures[remainIds, :2])
        _, groupNNIdx = kdtree.query(groupFeatures[toMergeIds, :2], k=min(PR_MIN_NN3, len(remainIds)))
        groupNNIdx=np.transpose(groupNNIdx)[:,np.newaxis]  if groupNNIdx.ndim ==1 else groupNNIdx
        nNNs = groupNNIdx.shape[1]
        
        # Calculate similarity score based on gaps and overlaps
        for i,toMergeId in enumerate(toMergeIds):
            currentClusterCentroids = clusterGroupMap[np.concatenate([clusterMapVGroup[toMergeId]]),:]
            filterMetrics = np.zeros([nNNs, 5])
            for j in range(nNNs):
                remainId = remainIds[groupNNIdx[i, j]]
                line1Ends = [groupFeatures[toMergeId, 3], groupFeatures[toMergeId, 3] + groupFeatures[toMergeId, 4]]
                line2Ends = [groupFeatures[remainId, 3], groupFeatures[remainId, 3] + groupFeatures[remainId, 4]]
                lineSegs = [(line2Ends[1]- line1Ends[0]), (line1Ends[1] - line2Ends[0])]
                verticalOverlapRatio = np.min(lineSegs) / np.max(lineSegs)
                if groupHulls[toMergeId] is not None and groupHulls[remainId] is not None:
                    horizontalOverlapRatio = overlapping(groupHulls[toMergeId], groupHulls[remainId])
                else:
                    horizontalOverlapRatio = 0.0

                nnClusterCentroids = clusterGroupMap[np.concatenate([clusterMapVGroup[remainId]]),:]

                kdtree = cKDTree(nnClusterCentroids[:, :3])
                nnDs, idx = kdtree.query(currentClusterCentroids[:, :3], k=1)
                min3DSpacing = np.min(nnDs)
                min2DSpacing = np.linalg.norm(np.mean(nnClusterCentroids[:, :2], 0)-np.mean(currentClusterCentroids[:, : 2], 0))
                filterMetrics[j,:]=np.array([horizontalOverlapRatio, verticalOverlapRatio, min3DSpacing, min2DSpacing, remainId])
            filterMetrics[filterMetrics[:, 1] <= 0, 1]=0
            score = np.exp(-np.power(1 - filterMetrics[:, 0],2) - PR_VERTICAL_WEIGHT * np.power(1 - filterMetrics[:, 1],2) - np.power(np.min(filterMetrics[:, 2:4],1) / sigmaD,2))

            scoreSortI = score.argsort()[::-1]
            scoreSort=score[scoreSortI]
            if scoreSort[0] == 0:
                continue
            scoreSortRatio = scoreSort / scoreSort[0] # Normalize score based on the largest score
            scoreSortCandidateIdx = np.where(scoreSortRatio > PR_SCORE_CANDIDATE_THRESH)[0]# Filter only the large scores as candidates
            nScoreSortCandidateIdx = len(scoreSortCandidateIdx)
            if nScoreSortCandidateIdx == 1:
                mergeNNId = groupU[int(filterMetrics[scoreSortI[scoreSortCandidateIdx[0]], -1])] # Tree segment ID to merge
            elif nScoreSortCandidateIdx > 1:
                filterMinSpacingIdx = np.argmin(filterMetrics[scoreSortI[scoreSortCandidateIdx], 2])# If there are more than one candidates, choose the one with minimal 3D point gap to the current tree segment
                mergeNNId = groupU[int(filterMetrics[scoreSortI[filterMinSpacingIdx], -1])] # Tree segment ID to merge
            else:
                continue
            clusterGroupIds[groupVGroup[toMergeIds[i]]]=mergeNNId # Update the point-level tree Ids

        # Re-group tree segments based on updated tree IDs
        clusterGroupMap[:, -1]=clusterGroupIds[clusterUIdx]
        clusterMapU, clusterMapV = np.unique(clusterGroupMap[:, -1], return_inverse=True)
        _, clusterMapVGroup = npi.group_by(clusterGroupMap[:, -1].astype(np.int32), np.arange(len(clusterGroupMap[:, -1])))
        iter = iter + 1
        mergedRemainIds.extend(groupU[remainIds])

    # For the remaining unmerged non-stem segments, merge each to the nearest segment with minimal 3D point gap
    unmergeIds=np.setdiff1d(groupU,mergedRemainIds)
    mergedRemainIds=np.unique(mergedRemainIds)

    unmergeIds = np.where(np.isin(clusterMapU, unmergeIds))[0]
    mergedRemainIds = np.where(np.isin(clusterMapU, mergedRemainIds))[0]

    kdtree = cKDTree(groupFeatures[unmergeIds, :2])
    _, groupNNIdx = kdtree.query(groupFeatures[mergedRemainIds, :2], k=min(PR_MIN_NN3, len(mergedRemainIds)))
    groupNNIdx = np.transpose(groupNNIdx)[:, np.newaxis] if groupNNIdx.ndim == 1 else groupNNIdx
    nNNs = groupNNIdx.shape[1]

    for i,unmergeId in enumerate(unmergeIds):
        currentClusterCentroids = clusterGroupMap[np.concatenate(clusterMapVGroup[unmergeId]),:]
        filterMetrics = np.zeros([nNNs, 2])
        for j in range(nNNs):
            mergedRemainId = mergedRemainIds[groupNNIdx[i, j]]
            nnClusterCentroids = clusterGroupMap[np.concatenate(clusterMapVGroup[mergedRemainId]),:]

            kdtree = cKDTree(currentClusterCentroids[:, :3])
            nnDs, idx = kdtree.query(nnClusterCentroids[:, :3])

            min3DSpacing = min(nnDs)
            filterMetrics[j,:]=np.array([min3DSpacing, mergedRemainId])

        filterMinSpacingIdx=np.argmin(filterMetrics[:,0])
        mergeNNId=groupU[filterMetrics[filterMinSpacingIdx,-1]]
        clusterGroupIds[groupVGroup[unmergeIds[i]]]=mergeNNId
    return clusterGroupIds

def decimate_pcd(columns, min_res):
    """Resample the point cloud to a lower resolution.

    Args:
        columns: Point cloud data columns
        min_res: Desired minimum resolution
    """
    _, block_idx_uidx, block_inverse_idx = np.unique(np.floor(columns[:, :3] / min_res).astype(np.int32), axis=0, return_index=True, return_inverse=True)
    return block_idx_uidx, block_inverse_idx

def main():
    """Main function to process laser scanning point clouds."""
    print('Individual-tree isolation (treeiso) from terrestrial laser scanning point clouds')
    print('**Ground points should be already removed')
    print('**Output will be saved to the same directory of the input path')
    print('The University of Lethbridge - Artemis Lab')
    print('Copyright - Zhouxin Xi (zhouxin.xi@uleth.ca) and Chris Hopkinson (c.hopkinson@uleth.ca)')

    path_input = 'LPine1_demo.laz'
    chunk_range = [10_000, 50_000, 100_000, 250_000, 300_000, 500_000, 800_000, 1_000_000]
    for chunk_size in chunk_range:
        with laspy.open(path_input) as f:
            for points in f.chunk_iterator(chunk_size):

                print('*******Processing******* ')
                pcd=np.transpose([points.x,points.y,points.z])
                pcd=pcd-np.mean(pcd[:,:3],axis=0)

                dec_idx_uidx, dec_inverse_idx = decimate_pcd(pcd[:, :3], PR_DECIMATE_RES1)  # reduce points first
                pcd_dec = pcd[dec_idx_uidx]

                # Initial segmentation in 3D
                init_labels=init_segs(pcd_dec)

                # Intermediate segmentation in 2D
                intermediate_labels=intermediate_segs(np.concatenate([pcd_dec,init_labels[:,np.newaxis]],axis=-1))

                # Final segmentation based on segment similarity
                labels=final_segs(np.concatenate([pcd_dec,init_labels[:,np.newaxis],intermediate_labels[:,np.newaxis]],axis=-1))
                print('*******End processing*******')

if __name__ == '__main__':
    main()
```

**Comment by truebelief** [comment]
Thank you for your patience. There's nothing wrong with your environment settings. The code you provided is an excellent test example with many discontinued points. I assume most users will likely work with standard forest scans without those non-tree shapes, but this test gives me more confidence that the script is robust against irregular shapes.

I've created fixes in the [new branch](https://github.com/truebelief/artemis_treeiso/tree/treeiso_python_testing) (commit aaabf39). The issue mainly occurred when there was only one component or when the component count was lower than the KNN's K. The code you provided should work now. Please try updating the main function with your version using chunks to test it again.

I've also fixed some issues with PR_DECIMATE_RES2 and updated the main function to accept CSV files. It'll be a day or two before I build pre-built wheels so that the C++ version of the cut-pursuit algorithm can run in Python. It should be much faster once that's ready. Let me know if you run into any further problems.

**Comment by kalmary** [comment]
Thank you so much!!! I will test it thoroughly at work tomorrow and let you know. Looking forward for C++ update too :)

**Comment by kalmary** [comment]
Hello Zhouxin,

Seems like everything work as intended (in c++ aided branch too). Thank you again!

Only one thing I am missing is a possibility to preserve the input number of points as an output. For now output shape is always equal to number after first decimation.

EDIT: 0
Nevermind. I didn't quite understand the logic behind new indexing. Everything is working as intended. I will keep testing  the code and close the issue in a few days, if nothing new comes up.

**Comment by kalmary** [comment]
I just noticed; current update for C++ seems to be just a preparation for library import. The library cut_pursuit (from what I found on your another repo) isn't ready yet though, so I'm looking forward for  the update!

Rest of the code, just as before is working perfect, so I can close the issue

**Comment by kalmary** [comment]
Hello. I was a little to fast with closing the issue. I got one more. 

```
line 336, in final_segs
    currentClusterCentroids = clusterGroupMap[np.concatenate([clusterMapVGroup[toMergeId]]), :]
                                                              ~~~~~~~~~~~~~~~~^^^^^^^^^^^
IndexError: list index out of range
```
This one may be hard to fix. I get it with my data which I cannot really share. Point data is noisy, low quality and with no clearly visible borders between separate objects. Number of points to segment also differs. I get this issue once per several dozen of iterations (chunks).

 I will come back to loading  by chunks your cloud data.  If I will be able to get the error with LPine1_demo I'll give you the parameters to reproduce it.

**Comment by truebelief** [comment]
Thanks for your careful testing! I've updated the Python code in the main branch (under PythonCPP) to achieve faster performance. Could you please test your example using the new code? Let me know if you run into any issues.

**Comment by kalmary** [comment]
Hello! After updating to new version of PythonCPP branch I got following error:
```
line 162, in create_node_edges
    nn_idx = indices[i, 1:]
             ~~~~~~~^^^^^^^
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```
Indices matrix had shape: (1,).

My venv is configured with new requirements.txt file you provided in cpp branch

**Comment by kalmary** [comment]
One more :( 
Maybe I should have started another issue for errors in PythonCPP branch. Excuse me, I hope it will not create a mess for now.

In branch python testing with specific configuration:
```
# Parameters
PR_REG_STRENGTH1 = 1.5  # lambda1
PR_MIN_NN1 = 15  # K1: key parameter

PR_REG_STRENGTH2 = 25  # lambda2: key parameter
PR_MIN_NN2 = 20  # K2: key parameter

PR_DECIMATE_RES1 = 0.1  # For speed optimization
PR_DECIMATE_RES2 = 0.2  # For speed optimization
PR_MAX_GAP = 0.5 # Max assumed point gap within a tree due to occlusion

PR_REL_HEIGHT_LENGTH_RATIO = 0.5  # rho
PR_VERTICAL_WEIGHT = 0.5  # w
PR_MIN_NN3 = 20  # trivial
PR_SCORE_CANDIDATE_THRESH = 0.7  # No need to change
PR_INIT_STEM_REL_LENGTH_THRESH = 1.5  # No need to change
```
I got following error:
```
line 349, in final_segs
    nnClusterCentroids = clusterGroupMap[np.concatenate([clusterMapVGroup[remainId]]), :]
                                                         ~~~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
```

I get it once for several dozen with noisy and varying size data which makes it hard to create find some reproductible case with LPine1_demo.laz

**Comment by truebelief** [comment]
Would you mind sharing one of your data samples with me? Sometimes an algorithm can be too closely tied to the specific dataset it was developed on, and I'd like to see if I can decouple it by adding some extra filtering steps. Thanks,

**Comment by kalmary** [comment]
I know it sounds problematic but I really cannot share any data. One thing I noticed (maybe that's the cause) it happens mostly when I set absurdly low PR_MAX_GAP, which was my solution for merging far away clusters by the program. I will think of any solution to help you reproduce the issue

**Comment by truebelief** [comment]
> Hello! After updating to new version of PythonCPP branch I got following error:
> 
> ```
> line 162, in create_node_edges
>     nn_idx = indices[i, 1:]
>              ~~~~~~~^^^^^^^
> IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
> ```
> 
> Indices matrix had shape: (1,).
> 
> My venv is configured with new requirements.txt file you provided in cpp branch

I don't need to debug this with data: it's clear that the issue arises because there are no clusters (or only one cluster) within the default gap threshold of 1.0 m. This randomness occurs because of the chunk-based method, which creates isolated point sets with a minimum point spacing exceeding 1.0 m.

You can always add a simple condition to skip situations when the group size is one, which would prevent errors. But honestly, I don't quite understand why you prefer using chunk-based data reading instead of tiling or other methods that preserve the local connectivity, which is the algorithm's only loose requirement. Without your specific data, I can't replicate exactly what's happening, and I'd prefer not to try to accommodate every possible data input, especially completely random or sparse data that inherently violate the algorithm design principles and guarantee poor segmentation results.

In your testing scenario, using a simple try-except block around the function could let the algorithm continue without interruption, though at some small cost to processing speed.

**Comment by kalmary** [comment]
Hello! I am sorry for no contact for quite a while. 
I have not came up with any solution how I could share with you the data I use. On the other hand I found out that using exceptions and if statements mix for too few clusters/ number of points is good enough solution for my use case. Thank you for your advise about data tiling. My choice of chunking is caused mainly by its simplicity. Preprocessed data I get in this project is cut in a way I can't ever guarantee 100% clusters connectivity.

**Comment by truebelief** [comment]
@kalmary Thanks very much for your patience. The try-except way is usually a last resort. Please let me know if you run into any further issues. I'm also working on a new plugin, TreeAIBox (a CloudCompare Python plugin), which might work better, but it'll need some time to finish.
